### ISSUE TITLE
Infinite more loading

### ISSUE THREAD

**Issue by yarolegovich** [Malinskiy/SuperRecyclerView#20]
Hi, I can't figure out how to specify when to load more items to the list. And how to stop this process. It starts loading more after short up swipe and never stops.

**Comment by kimbeejay** [comment]
Maybe RecyclerView.hideMoreProgress() ?

**Comment by yarolegovich** [comment]
No, I extract data from a site on more call, and program starts infinite calling, extracting more and more. Problem is not in progress bar.

**Comment by Malinskiy** [comment]
Hi @yarolegovich!

@kimbeejay was actually right, you have to use hideMoreProgress() to hide the bottom progress bar, maybe you do it in the wrong place? You actually have to hide it every time in [onMoreAsked](https://github.com/Malinskiy/SuperRecyclerView/blob/master/SuperRecyclerView/src/main/java/com/malinskiy/superrecyclerview/OnMoreListener.java#L9) is called (it's every time a user scrolls the view).

Consider also using the [max](https://github.com/Malinskiy/SuperRecyclerView/blob/master/SuperRecyclerView/src/main/java/com/malinskiy/superrecyclerview/SuperRecyclerView.java#L439) parameter to be large so that you download the data from API before the user actually scrolled to the still-not-loaded positions.

**Comment by yarolegovich** [comment]
Thanks, thing was in max parameter.
